name: ci
on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'typings/**'
      - 'package.json'
      - 'yarn.lock'
    branches:
      - '*'
      - '!master'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: ci.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 30
          persist-credentials: false

      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent

      - name: Test
        run: |
          yarn test
